-intstyle "ise" -incremental -o "C:/Users/aula/Downloads/ProjetoFinal_v2/ProjetoFinal/main_tb_isim_beh.exe" -prj "C:/Users/aula/Downloads/ProjetoFinal_v2/ProjetoFinal/main_tb_beh.prj" "work.main_tb" 
